// Generated by Selenium IDE
import org.junit.Test;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import java.util.concurrent.TimeUnit;

public class ProductTest extends BaseTest {

  @Test
  public void aProductIsCreatedWhenAllFormFieldsAreFilled() {
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    vars.put("productName", "product to be tested");
    driver.findElement(By.cssSelector(".forceActionLink > div")).click();
    driver.findElement(By.xpath("((//div[contains(@class,'slds-grid slds-gutters_small')])[1]/div)[1]//input")).sendKeys(vars.get("productName").toString());
    driver.findElement(By.xpath("((//div[contains(@class,'slds-grid slds-gutters_small')])[1]/div)[2]//input")).click();
    driver.findElement(By.xpath("((//div[contains(@class,'slds-grid slds-gutters_small')])[2]/div)[1]//input")).sendKeys("Product code");
    driver.findElement(By.xpath("((//div[contains(@class,'slds-grid slds-gutters_small')])[2]/div)[2]//a")).click();
    driver.findElement(By.linkText("None")).click();
    driver.findElement(By.xpath("(//div[contains(@class,'slds-grid slds-gutters_small')])[3]/div//textarea")).sendKeys("Product Description");
    driver.findElement(By.cssSelector(".forceActionButton:nth-child(3) > .label")).click();
    assertThat(driver.findElement(By.cssSelector(".slds-page-header__title > .uiOutputText")).getText(), is(vars.get("productName").toString()));
    driver.close();
  }
  @Test
  public void aProductIscreatedWhenJustTheRequiredFormFieldsAreFilled() {
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    vars.put("productName", "product to be tested");
    driver.findElement(By.cssSelector(".forceActionLink > div")).click();
    driver.findElement(By.xpath("((//div[contains(@class,'slds-grid slds-gutters_small')])[1]/div)[1]//input")).sendKeys(vars.get("productName").toString());
    driver.findElement(By.cssSelector(".forceActionButton:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector(".slds-page-header__title > .uiOutputText")).getText(), is(vars.get("productName").toString()));
    driver.close();
  }
}
